### ISSUE TITLE
Need dep attrs>=19.2

### ISSUE THREAD

**Issue by michaelkarlcoleman** [conda-forge/fastscape-feedstock#1]
It appears that fastscape depends on 'attrs>=19.2'.  (There was a backward-incompatible change in attrs at that version.)

**Comment by benbovy** [comment]
This has to be fixed in xarray-simlab. Are you referring to this issue https://github.com/benbovy/xarray-simlab/issues/66?

**Comment by michaelkarlcoleman** [comment]
I guess it's the same issue.  Was moving quickly, but when I encountered the error, noted that in a previous case, adding an 'attrs' version constraint would solve the problem.
